export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as VerifyEmail } from './VerifyEmail'
export { default as ResetPassword } from './ResetPassword'
export { default as Video } from './Video'
export { default as Chat } from './Chat'
